stages:
  - .pre
  - build
  - packaging
  - .post

include:
  - local: pipelines/ubuntu-22_04.yml
  - local: pipelines/ubuntu-22_04-java.yml
  - local: pipelines/ubuntu-22_04-python.yml
  - local: pipelines/ubuntu-22_04-nodejs.yml

